os: linux
arch: arm64-graviton2
virt: vm
group: edge
dist: focal
services:
  - docker

env:
  - PYVER=39
  - PYVER=38
  - PYVER=37
  - PYVER=36

jobs:
  include:
    - env: PYVER=39
    - env: PYVER=38
    - env: PYVER=37
    - env: PYVER=36

before_install:
  - bash check-arch.sh
  - docker pull "kumatea/build:py$PYVER-ci"

install:
  - mkdir whl
  - docker run --name "py$PYVER" -v "$(pwd):/build" "kumatea/build:py$PYVER-ci" /bin/bash -c "cd /build && bash run.sh $PYVER"

script:
  - DATETODAY=$(date -I | tr -d "-")
  - tar -cJf "$DATETODAY-$PYVER.tar.xz" whl
  - mkdir artifacts
  - cp "$DATETODAY-$PYVER.tar.xz" artifacts/

deploy:
  provider: gcs
  access_key_id: "$GCSKEYID"
  secret_access_key: "$GCSKEYSEC"
  bucket: "pytorch-aarch64"
  skip_cleanup: true
  cleanup: false
  on:
    branch: ci-whl
  local-dir: artifacts
  run: echo "Uploaded successfully!"
