os: linux
arch: arm64-graviton2
virt: vm
group: edge
dist: focal
services:
  - docker

env: PYVER=39

before_install:
  - bash check_arch.sh
  - docker pull python:3.9-slim

install:
  - mkdir whl
  - mkdir whl/171 && mkdir whl/170 && mkdir whl/160 && mkdir whl/151 && mkdir whl/150 && mkdir whl/141 && mkdir whl/140
  - docker run --name "py$PYVER" -v $(pwd):/test python:3.9-slim /bin/bash -c "cd /test && bash test.sh"

script:
  - tar -cJf "whl-$PYVER.tar.xz" build
  - mkdir artifacts
  - cp "whl-$PYVER.tar.xz" artifacts/

deploy:
  provider: gcs
  access_key_id: "$GCSKEYID"
  secret_access_key: "$GCSKEYSEC"
  bucket: "pytorch-aarch64"
  skip_cleanup: true
  cleanup: false
  on:
    branch: ci-whl
  local-dir: artifacts
  run: echo "Uploaded successfully!"
